### ISSUE TITLE
Preserve empty lines

### ISSUE THREAD

**Issue by orest22** [putoutjs/printer#1]
Is there an easy way to preserve empty lines?

Example:

![image](https://github.com/putoutjs/printer/assets/1497502/24df27fe-f214-486f-9887-e8cbc915f177)

**Comment by coderaiser** [comment]
Why do you need this? There is no such an option since `@putout/printer` is opinionated printer, but it supports a lot of overrides, and you can copy [`ImportDeclaration`](https://github.com/putoutjs/printer/blob/v7.1.2/lib/tokenize/statements/import-declaration/import-declaration.js), and [override](https://github.com/putoutjs/printer#overrides) visitor, so it printed in a way you like.

**Comment by orest22** [comment]
@coderaiser Mostly curious if I haven't missed any configs before writing custom visitors. Thanks for the answer 👍
